# .readthedocs.yml
# Read the Docs configuration file
version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - htmlzip
  - pdf

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - requirements: docs/requirements.txt
