name: Sphinx

on:
  push:

jobs:
  sphinx-build:
    name: Sphinx Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        format:
          - html
          - epub
          - latex

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip
          cache-dependency-path: |
            **/requirements*.txt
            
      - name: Install fonts
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install ghostscript fonts-freefont-otf

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Run Sphinx
        run: |
          cd docs
          make SPHINXOPTS="-W --keep-going -n" ${{ matrix.format }}
